name: "Trufflehog"

on:
  push:
    branches: 
      - main
      - test  # Add your test branch here
  pull_request:
    branches: 
      - main
      - test  # Add your test branch here
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  ScanSecrets:
    name: Scan secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Run TruffleHog in Docker
        run: |
          docker run --rm -v "${GITHUB_WORKSPACE}:/pwd" trufflesecurity/trufflehog:latest github --org=trufflesecurity --include-detectors=all --only-verified
